Личный проект: доверяй, но проверяй (часть 2)
htmlacademy-javascript/1106215-keksobooking-21 pull request #5
Opened 2020-10-23 17:44 UTC by whoisdaria

2020-10-23 17:46 UTC, whoisdaria commented on js/main.js
> +    userPin.addEventListener(`click`, onPinClick);
а снимать надо обработчики с карточек, которые закрыты ?

2020-10-24 14:53 UTC, balesniy requested changes

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +  mainPin.removeEventListener(`keydown`, onMainPinKeydown);
чтобы не повторять код в обработчиках, можно перенести его в setActiveMode

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +  if (priceValue > MAX_PRICE) {
можно оформить тернарный в setCustomValidity

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +  const closeCard = () => {
карточку нужно совсем удалить, можно методом remove на элементе, иначе они копятся в странице

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +      closeCard();
при закрытии карточки нужно снять обработчик с документа

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +  card.addEventListener(`click`, onButtonCloseClick);
обработчик нужно поставить на кнопку закрытия

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +    // чтобы обособить обработчик, нужно туда передать аргумент items, но не понимаю как
можно сделать функцию-установщик обработчика, и передавать в нее аргументом нужный элемент item

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +      const card = renderCard(items[i]);
по тз при клике еще нужно подсветить классом текущий пин и снять его при закрытии карточки

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +        map.removeChild(oldCard);
имеет смысл оформить отдельную функцию для закрытия карточки, использовать ее тут и при клике по кнопке или по esc

2020-10-24 14:53 UTC, balesniy commented on js/main.js
> +    userPin.addEventListener(`click`, onPinClick);
если карточку удалять, то обработчик с элемента сам удалится, но если скрывать, то они копятся. отдельно нужно снимать обработчик esc

2020-10-29 15:59 UTC, balesniy requested changes
все еще нужно поработать с обработчиками

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +  window.removeEventListener(`keydown`, onEscapeKeydown(item));
- при закрытии карточки еще нужно снять активный класс с пина
- onEscapeKeydown возвращает функцию, она каждый раз новая, то есть ссылка другая и так ее не снять

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +const onEscapeKeydown = (item) => (evt) => {
если onEscapeKeydown уже не обработчик а функция-фабрика обработчиков, то ей нужно дать соответствующее имя

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +  window.addEventListener(`keydown`, onEscapeKeydown(card));
этот обработчик будет не снять

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +  allPins.forEach((element) => {
лишний цикл по элементам, активный у нас только один, можно его или хранить в переменной или уточнить селектор

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +const onPinClick = (pin) => () => {
тут такая же история с именованием функций как и выше

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +  map.insertBefore(card, map.querySelector(`.map__filters-container`));
лишний поиск по селектору, элемент-контейнер не меняется, достаточно найти его один раз и сохранить в переменную

2020-10-29 15:59 UTC, balesniy commented on js/main.js
> +  // не понимаю почему не присваивается класс
он присваивается, но элемент вне страницы, const userPin = renderPin(pin); - возвращает новый элемент. нам нужно или получить актуальный через объект события, или в параметрах, или через замыкание

2020-10-30 13:10 UTC, whoisdaria reviewed
вопрос со снятием обработчика с window - если снимаю его в closeCard, почему то  при рендере новой карточки он не появляется , хотя должен

2020-10-30 16:52 UTC, balesniy requested changes

2020-10-30 16:52 UTC, balesniy commented on js/main.js
> +  openedCard.remove();
при удалении карточки нужно снять обработчик с window

2020-10-30 16:52 UTC, balesniy commented on js/main.js
> +    window.removeEventListener(`keydown`, keydownHandler);
удалить обработчик нужно при закрытии карточки

2020-11-03 11:37 UTC, merged